# Generated by Django 5.2.8 on 2025-12-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers_alter_payment_paid_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_checkout_url",
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Ссылка на оплату в Stripe",
            ),
        ),
    ]
