# Generated by Django 5.2.8 on 2025-12-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="время последней рассылки об обновлении",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="время последнего изменения курса"
            ),
        ),
    ]
